---
book_repo: pivotal-cf/docs-book-cloud-cache
layout_repo: pivotal-cf/docs-layout-repo
layout_repo_ref: master
feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true


sections:
- repository:
    name: pivotal-cf/docs-services-partials
    ref: master
  directory: p-cloud-cache/odb
  no_docs: true

- repository:
    name: pivotal-cf/docs-cloud-cache
    ref: 'v1.5-branch'
    at_path: content
  directory: p-cloud-cache/1-5
  subnav_template: cloudcache_subnav-1-5.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.5
    changelog_href: http://docs.pivotal.io/p-cloud-cache/1-5/release-notes.html
    local_header_img: /images/cloud_rings.png
    local_header_title: Pivotal Cloud Cache for PCF
    search_placeholder: Search Pivotal Cloud Cache for PCF 1.5
    url_prefix: p-cloud-cache/1-5
    local_product_version: 1.5
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/p-cloud-cache/1-4
        display_name: v1.4
      - url_prefix: http://docs.pivotal.io/p-cloud-cache/1-3
        display_name: v1.3
      - url_prefix: http://docs.pivotal.io/p-cloud-cache/1-2
        display_name: v1.2
      - url_prefix: http://docs.pivotal.io/p-cloud-cache/1-1
        display_name: v1.1
      - url_prefix: http://docs.pivotal.io/p-cloud-cache/1-0
        display_name: v1.0

- repository:
    name: pivotal-cf/docs-cloud-cache
    ref: 'v1.4-branch'
    at_path: content
  directory: p-cloud-cache/1-4
  subnav_template: cloudcache_subnav-1-4.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.5
    changelog_href: http://docs.pivotal.io/p-cloud-cache/1-4/release-notes.html
    local_header_img: /images/cloud_rings.png
    local_header_title: Pivotal Cloud Cache for PCF
    search_placeholder: Search Pivotal Cloud Cache for PCF 1.4
    url_prefix: p-cloud-cache/1-4
    local_product_version: 1.4
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/p-cloud-cache/1-5
        display_name: v1.5
      - url_prefix: http://docs.pivotal.io/p-cloud-cache/1-3
        display_name: v1.3
      - url_prefix: http://docs.pivotal.io/p-cloud-cache/1-2
        display_name: v1.2
      - url_prefix: http://docs.pivotal.io/p-cloud-cache/1-1
        display_name: v1.1
      - url_prefix: http://docs.pivotal.io/p-cloud-cache/1-0
        display_name: v1.0

- repository:
    name: pivotal-cf/docs-cloud-cache
    ref: 'v1.3-branch'
    at_path: content
  directory: p-cloud-cache/1-3
  subnav_template: cloudcache_subnav-1-3.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.5
    changelog_href: http://docs.pivotal.io/p-cloud-cache/1-3/release-notes.html
    local_header_img: /images/cloud_rings.png
    local_header_title: Pivotal Cloud Cache for PCF
    search_placeholder: Search Pivotal Cloud Cache for PCF 1.3
    url_prefix: p-cloud-cache/1-3
    local_product_version: 1.3
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/p-cloud-cache/1-5
        display_name: v1.5
      - url_prefix: http://docs.pivotal.io/p-cloud-cache/1-4
        display_name: v1.4
      - url_prefix: http://docs.pivotal.io/p-cloud-cache/1-2
        display_name: v1.2
      - url_prefix: http://docs.pivotal.io/p-cloud-cache/1-1
        display_name: v1.1
      - url_prefix: http://docs.pivotal.io/p-cloud-cache/1-0
        display_name: v1.0

- repository:
    name: pivotal-cf/docs-cloud-cache
    ref: 'v1.2-branch'
    at_path: content
  directory: p-cloud-cache/1-2
  subnav_template: cloudcache_subnav-1-2.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.5
    changelog_href: http://docs.pivotal.io/p-cloud-cache/1-2/release-notes.html
    local_header_img: /images/cloud_rings.png
    local_header_title: Pivotal Cloud Cache for PCF
    search_placeholder: Search Pivotal Cloud Cache for PCF 1.2
    url_prefix: p-cloud-cache/1-2
    local_product_version: 1.2
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/p-cloud-cache/1-5
        display_name: v1.5
      - url_prefix: http://docs.pivotal.io/p-cloud-cache/1-4
        display_name: v1.4
      - url_prefix: http://docs.pivotal.io/p-cloud-cache/1-3
        display_name: v1.3
      - url_prefix: http://docs.pivotal.io/p-cloud-cache/1-1
        display_name: v1.1
      - url_prefix: http://docs.pivotal.io/p-cloud-cache/1-0
        display_name: v1.0

- repository:
    name: pivotal-cf/docs-cloud-cache
    ref: 'v1.1-branch'
    at_path: content
  directory: p-cloud-cache/1-1
  subnav_template: cloudcache_subnav-1-1.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.5
    changelog_href: http://docs.pivotal.io/p-cloud-cache/1-1/release-notes.html
    local_header_img: /images/cloud_rings.png
    local_header_title: Pivotal Cloud Cache for PCF
    search_placeholder: Search Pivotal Cloud Cache for PCF 1.1
    url_prefix: p-cloud-cache/1-1
    local_product_version: 1.1
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/p-cloud-cache/1-5
        display_name: v1.5
      - url_prefix: http://docs.pivotal.io/p-cloud-cache/1-4
        display_name: v1.4
      - url_prefix: http://docs.pivotal.io/p-cloud-cache/1-3
        display_name: v1.3
      - url_prefix: http://docs.pivotal.io/p-cloud-cache/1-2
        display_name: v1.2
      - url_prefix: http://docs.pivotal.io/p-cloud-cache/1-0
        display_name: v1.0

- repository:
    name: pivotal-cf/docs-cloud-cache
    ref: 'v1.0-branch'
    at_path: content
  directory: p-cloud-cache/1-0
  subnav_template: cloudcache_subnav.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.5
    changelog_href: http://docs.pivotal.io/p-cloud-cache/1-0/release-notes.html
    local_header_img: /images/cloud_rings.png
    local_header_title: Pivotal Cloud Cache for PCF
    search_placeholder: Search Pivotal Cloud Cache for PCF 1.0
    url_prefix: p-cloud-cache/1-0
    local_product_version: 1.0
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/p-cloud-cache/1-5
        display_name: v1.5
      - url_prefix: http://docs.pivotal.io/p-cloud-cache/1-4
        display_name: v1.4
      - url_prefix: http://docs.pivotal.io/p-cloud-cache/1-3
        display_name: v1.3
      - url_prefix: http://docs.pivotal.io/p-cloud-cache/1-2
        display_name: v1.2
      - url_prefix: http://docs.pivotal.io/p-cloud-cache/1-1
        display_name: v1.1
